services:
  app:
    build:
      context: .
    image: stonks-app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Mount local code for hot reload
      - /app/node_modules # Keep container-installed dependencies
    command: sh -c "npm install && npm run dev"
