version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true    # safer hot reload in containers
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
